import {
  Activity,
  AlarmClock,
  Award,
  Baby,
  Bell,
  Bike,
  Bird,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Bug,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  ChartColumn,
  ChartLine,
  CircleCheck,
  Clock,
  CloudSun,
  Code,
  Coffee,
  CreditCard,
  Database,
  Dog,
  Dumbbell,
  FileText,
  Film,
  Fish,
  Flag,
  Flower2,
  Folder,
  Gamepad2,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  House,
  ImageIcon,
  KeyRound,
  Lamp,
  Languages,
  Leaf,
  Lightbulb,
  LinkIcon,
  ListChecks,
  Lock,
  Mail,
  MapIcon,
  MapPin,
  MessageCircle,
  Mic,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Notebook,
  Package,
  Paintbrush,
  Palette,
  PenTool,
  PiggyBank,
  Pill,
  Plane,
  Plug,
  Puzzle,
  Receipt,
  Rocket,
  Rss,
  Ruler,
  Scale,
  Scissors,
  Search,
  Server,
  Shield,
  Shirt,
  ShoppingCart,
  Smile,
  Sofa,
  Sparkles,
  Sprout,
  SquareTerminal,
  Star,
  Sun,
  Tag,
  Target,
  Thermometer,
  Ticket,
  Timer,
  TrainFront,
  Trees,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Waves,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * The glyphs a Conch app's icon may use (mirrors `APP_GLYPHS` in
 * `@conch/protocol`; Nacre stays free of it). The web passes the protocol's
 * `AppGlyph` here, so a glyph added there and not here fails its typecheck.
 */
export const APP_GLYPHS = [
  'sparkles',
  'leaf',
  'sprout',
  'flower',
  'trees',
  'mountain',
  'waves',
  'book-open',
  'notebook',
  'list-checks',
  'circle-check',
  'calendar',
  'clock',
  'alarm-clock',
  'timer',
  'bell',
  'plane',
  'train-front',
  'car',
  'bike',
  'map',
  'map-pin',
  'globe',
  'cloud-sun',
  'umbrella',
  'thermometer',
  'sun',
  'moon',
  'house',
  'lamp',
  'plug',
  'sofa',
  'wallet',
  'piggy-bank',
  'receipt',
  'credit-card',
  'chart-line',
  'chart-column',
  'trending-up',
  'shopping-cart',
  'gift',
  'ticket',
  'utensils',
  'coffee',
  'wine',
  'dumbbell',
  'heart-pulse',
  'heart',
  'activity',
  'pill',
  'baby',
  'dog',
  'cat',
  'fish',
  'bird',
  'music',
  'headphones',
  'mic',
  'film',
  'video',
  'tv',
  'gamepad',
  'camera',
  'image',
  'palette',
  'paintbrush',
  'pen-tool',
  'scissors',
  'shirt',
  'code',
  'terminal',
  'bug',
  'git-branch',
  'database',
  'server',
  'mail',
  'message-circle',
  'users',
  'user',
  'smile',
  'briefcase',
  'graduation-cap',
  'lightbulb',
  'search',
  'bookmark',
  'tag',
  'hash',
  'folder',
  'file-text',
  'link',
  'star',
  'award',
  'trophy',
  'target',
  'flag',
  'zap',
  'rocket',
  'puzzle',
  'shield',
  'key',
  'lock',
  'wrench',
  'hammer',
  'package',
  'box',
  'truck',
  'newspaper',
  'rss',
  'languages',
  'calculator',
  'ruler',
  'scale',
] as const;
export type AppGlyph = (typeof APP_GLYPHS)[number];

/** The colours an app's tile may take (mirrors `APP_COLORS`): `--nc-app-<colour>`. */
export const APP_COLORS = [
  'red',
  'orange',
  'amber',
  'yellow',
  'lime',
  'green',
  'teal',
  'cyan',
  'blue',
  'indigo',
  'violet',
  'pink',
  'slate',
] as const;
export type AppColor = (typeof APP_COLORS)[number];

/** Every glyph's Lucide icon. A `Record`, so a glyph without one doesn't compile. */
export const APP_GLYPH_ICONS: Record<AppGlyph, LucideIcon> = {
  sparkles: Sparkles,
  leaf: Leaf,
  sprout: Sprout,
  flower: Flower2,
  trees: Trees,
  mountain: Mountain,
  waves: Waves,
  'book-open': BookOpen,
  notebook: Notebook,
  'list-checks': ListChecks,
  'circle-check': CircleCheck,
  calendar: Calendar,
  clock: Clock,
  'alarm-clock': AlarmClock,
  timer: Timer,
  bell: Bell,
  plane: Plane,
  'train-front': TrainFront,
  car: Car,
  bike: Bike,
  map: MapIcon,
  'map-pin': MapPin,
  globe: Globe,
  'cloud-sun': CloudSun,
  umbrella: Umbrella,
  thermometer: Thermometer,
  sun: Sun,
  moon: Moon,
  house: House,
  lamp: Lamp,
  plug: Plug,
  sofa: Sofa,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  receipt: Receipt,
  'credit-card': CreditCard,
  'chart-line': ChartLine,
  'chart-column': ChartColumn,
  'trending-up': TrendingUp,
  'shopping-cart': ShoppingCart,
  gift: Gift,
  ticket: Ticket,
  utensils: Utensils,
  coffee: Coffee,
  wine: Wine,
  dumbbell: Dumbbell,
  'heart-pulse': HeartPulse,
  heart: Heart,
  activity: Activity,
  pill: Pill,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  fish: Fish,
  bird: Bird,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  film: Film,
  video: Video,
  tv: Tv,
  gamepad: Gamepad2,
  camera: Camera,
  image: ImageIcon,
  palette: Palette,
  paintbrush: Paintbrush,
  'pen-tool': PenTool,
  scissors: Scissors,
  shirt: Shirt,
  code: Code,
  terminal: SquareTerminal,
  bug: Bug,
  'git-branch': GitBranch,
  database: Database,
  server: Server,
  mail: Mail,
  'message-circle': MessageCircle,
  users: Users,
  user: User,
  smile: Smile,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  lightbulb: Lightbulb,
  search: Search,
  bookmark: Bookmark,
  tag: Tag,
  hash: Hash,
  folder: Folder,
  'file-text': FileText,
  link: LinkIcon,
  star: Star,
  award: Award,
  trophy: Trophy,
  target: Target,
  flag: Flag,
  zap: Zap,
  rocket: Rocket,
  puzzle: Puzzle,
  shield: Shield,
  key: KeyRound,
  lock: Lock,
  wrench: Wrench,
  hammer: Hammer,
  package: Package,
  box: Box,
  truck: Truck,
  newspaper: Newspaper,
  rss: Rss,
  languages: Languages,
  calculator: Calculator,
  ruler: Ruler,
  scale: Scale,
};

/** A glyph's icon; anything unknown (old data, a hand-edited file) gets the sparkle. */
export function appGlyphIcon(glyph: string): LucideIcon {
  return Object.hasOwn(APP_GLYPH_ICONS, glyph)
    ? APP_GLYPH_ICONS[glyph as AppGlyph]
    : APP_GLYPH_ICONS.sparkles;
}

/** A colour a tile can wear; anything unknown is slate. */
export function appColor(color: string): AppColor {
  return (APP_COLORS as readonly string[]).includes(color) ? (color as AppColor) : 'slate';
}
