import type { ReplayStep, ReplayTurn } from './RunReplay';

const T0 = Date.UTC(2026, 9, 8, 9, 0, 0);
const at = (s: number) => T0 + s * 1000;

/** A morning's coding chat: asked, thought, read, edited (after asking), tested, answered; then a second turn. */
export const REPLAY_STEPS: ReplayStep[] = [
  {
    id: 'a1',
    kind: 'asked',
    at: at(0),
    turn: 0,
    title: 'Fix the login test, it fails since yesterday',
    anchor: 'u1',
  },
  {
    id: 't0',
    kind: 'thought',
    at: at(1),
    durationMs: 4200,
    turn: 0,
    title: 'Thought it through',
    peek: 'The test expects a 200 but the handler returns 500 when the session is new. Probably the cookie check.',
  },
  {
    id: 'r1',
    kind: 'tool',
    family: 'explore',
    at: at(6),
    durationMs: 400,
    turn: 0,
    title: 'Read login.ts',
    detail: 'src/auth/login.ts',
    status: 'done',
    peek: 'export function login(req) {\n  if (!req.session) return 500;\n  …',
    anchor: 't1',
  },
  {
    id: 'g1',
    kind: 'tool',
    family: 'explore',
    at: at(7),
    durationMs: 300,
    turn: 0,
    title: 'Searched the code for “session”',
    detail: '14 matches',
    status: 'done',
    anchor: 't2',
  },
  {
    id: 'p1',
    kind: 'approval',
    at: at(9),
    durationMs: 6500,
    turn: 0,
    title: 'Edit src/auth/login.ts',
    detail: 'You allowed it',
    status: 'done',
    anchor: 't3',
  },
  {
    id: 'e1',
    kind: 'tool',
    family: 'edit',
    at: at(16),
    durationMs: 200,
    turn: 0,
    title: 'Changed login.ts',
    detail: 'src/auth/login.ts',
    status: 'done',
    diff: '-  if (!req.session) return 500;\n+  if (!req.session) req.session = newSession();',
    anchor: 't3',
  },
  {
    id: 'f1',
    kind: 'files',
    family: 'edit',
    at: at(16.3),
    turn: 0,
    title: 'Changed login.ts',
    status: 'done',
    files: [{ path: 'src/auth/login.ts', kind: 'changed' }],
  },
  {
    id: 'v1',
    kind: 'tool',
    family: 'verify',
    at: at(17),
    durationMs: 41_000,
    turn: 0,
    title: 'Ran the auth tests',
    detail: '1 failed',
    status: 'failed',
    peek: '✗ login › keeps the session (expected 200, got 302)\n23 passed, 1 failed',
    anchor: 't4',
  },
  {
    id: 'e2',
    kind: 'tool',
    family: 'edit',
    at: at(60),
    durationMs: 200,
    turn: 0,
    title: 'Changed login.ts',
    status: 'done',
    diff: '-  return redirect("/");\n+  return ok(session);',
    anchor: 't5',
  },
  {
    id: 'v2',
    kind: 'tool',
    family: 'verify',
    at: at(61),
    durationMs: 39_000,
    turn: 0,
    title: 'Ran the auth tests',
    detail: '24 passed',
    status: 'done',
    peek: '24 passed',
    anchor: 't6',
  },
  {
    id: 's1',
    kind: 'said',
    at: at(101),
    durationMs: 3000,
    turn: 0,
    title: 'Fixed: a new session no longer fails the check',
    peek: 'Fixed: a new session no longer fails the check. The test passes, and so do the other 23.',
    anchor: 'a2',
  },
  {
    id: 'a2',
    kind: 'asked',
    at: at(1900),
    turn: 1,
    title: 'Great, commit and push it',
    anchor: 'u2',
  },
  {
    id: 'c1',
    kind: 'tool',
    family: 'ship',
    at: at(1902),
    durationMs: 900,
    turn: 1,
    title: 'Committed “fix(auth): a new session passes”',
    status: 'done',
    anchor: 't7',
  },
  {
    id: 'b1',
    kind: 'tool',
    family: 'ship',
    at: at(1904),
    durationMs: 2100,
    turn: 1,
    title: 'Pushed to main',
    status: 'done',
    anchor: 't8',
  },
  {
    id: 's2',
    kind: 'said',
    at: at(1907),
    durationMs: 1000,
    turn: 1,
    title: 'Pushed to main.',
    peek: 'Pushed to main.',
    anchor: 'a3',
  },
];

export const REPLAY_TURNS: ReplayTurn[] = [
  {
    index: 0,
    at: at(0),
    endAt: at(104),
    usage: { inputTokens: 38_200, outputTokens: 2_900 },
    cost: { usd: 0.11, billing: 'metered' },
  },
  {
    index: 1,
    at: at(1900),
    endAt: at(1908),
    usage: { inputTokens: 9_100, outputTokens: 300 },
    cost: { usd: 0.02, billing: 'metered' },
  },
];
