/**
 * Pretend homes with each app's past chats, written in the shapes their own
 * code writes (ADR 0111): for the tests, and anyone trying the feature
 * without those apps. Keys in them are written in two parts, so no scanner
 * takes them for real ones (working agreement 6).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { zstdCompressSync } from 'node:zlib';

/** A key someone pasted into a chat once: it must never reach Conch. */
export const PASTED_KEY = 'sk-' + 'ant-api03-' + 'a'.repeat(32);

const jsonl = (lines: unknown[]) => `${lines.map((l) => JSON.stringify(l)).join('\n')}\n`;

function write(path: string, text: string | Buffer) {
  mkdirSync(join(path, '..'), { recursive: true });
  writeFileSync(path, text);
}

export const CLAUDE_SESSION = '0b6d1c2e-1111-4a4a-9b9b-000000000001';

/** `~/.claude/projects/-Users-me-shop/<session>.jsonl`, and what isn't a chat of yours. */
export function claudeHome(home: string) {
  const dir = join(home, '.claude', 'projects', '-Users-me-shop');
  const base = { cwd: '/Users/me/shop', sessionId: CLAUDE_SESSION, version: '2.1.0' };
  write(
    join(dir, `${CLAUDE_SESSION}.jsonl`),
    jsonl([
      { type: 'file-history-snapshot', snapshot: {} },
      {
        ...base,
        type: 'user',
        isMeta: true,
        timestamp: '2026-03-01T10:00:00.000Z',
        message: {
          role: 'user',
          content:
            'Caveat: The messages below were generated by the user while running local commands.',
        },
      },
      {
        ...base,
        type: 'user',
        timestamp: '2026-03-01T10:00:01.000Z',
        message: {
          role: 'user',
          content: `<command-name>/model</command-name>\nWhy does the checkout page double-charge? My key is ${PASTED_KEY}`,
        },
      },
      {
        ...base,
        type: 'assistant',
        timestamp: '2026-03-01T10:00:05.000Z',
        message: {
          id: 'msg_1',
          role: 'assistant',
          model: 'claude-sonnet-4-5',
          content: [{ type: 'thinking', thinking: 'secret reasoning' }],
        },
      },
      {
        ...base,
        type: 'assistant',
        timestamp: '2026-03-01T10:00:06.000Z',
        message: {
          id: 'msg_1',
          role: 'assistant',
          model: 'claude-sonnet-4-5',
          content: [{ type: 'text', text: 'The retry runs before the lock is taken.' }],
        },
      },
      {
        ...base,
        type: 'assistant',
        timestamp: '2026-03-01T10:00:07.000Z',
        message: {
          id: 'msg_1',
          role: 'assistant',
          content: [{ type: 'tool_use', id: 't1', name: 'Read', input: { file_path: 'pay.ts' } }],
        },
      },
      {
        ...base,
        type: 'user',
        timestamp: '2026-03-01T10:00:08.000Z',
        message: {
          role: 'user',
          content: [
            { type: 'tool_result', tool_use_id: 't1', content: 'export function pay() {}' },
          ],
        },
        toolUseResult: {},
      },
      {
        ...base,
        type: 'assistant',
        isSidechain: true,
        timestamp: '2026-03-01T10:00:09.000Z',
        message: {
          id: 'msg_2',
          role: 'assistant',
          content: [{ type: 'text', text: 'helper words' }],
        },
      },
      {
        ...base,
        type: 'assistant',
        timestamp: '2026-03-01T10:00:10.000Z',
        message: {
          id: 'msg_3',
          role: 'assistant',
          content: [{ type: 'text', text: 'Move the lock up a line and it charges once.' }],
        },
      },
      { type: 'ai-title', sessionId: CLAUDE_SESSION, aiTitle: 'Checkout double charge' },
      'not json at all',
    ]).replace('"not json at all"', '{"cut off'),
  );
  // Only steps, no words: not a conversation.
  write(
    join(dir, 'empty-session.jsonl'),
    jsonl([{ type: 'summary', summary: 'Nothing', leafUuid: 'x' }]),
  );
  // A helper's own transcript isn't a chat of yours.
  write(
    join(dir, CLAUDE_SESSION, 'subagents', 'agent-1.jsonl'),
    jsonl([{ ...base, type: 'user', message: { role: 'user', content: 'helper task' } }]),
  );
  return join(dir, `${CLAUDE_SESSION}.jsonl`);
}

export const CODEX_THREAD = '01a0f86d-d4ac-7672-82c7-36ac0fc067a6';

/** `~/.codex/sessions/2026/04/02/rollout-…-<thread>.jsonl`, an older squeezed one, and its title. */
export function codexHome(home: string) {
  const dir = join(home, '.codex');
  const lines = [
    {
      timestamp: '2026-04-02T09:00:00.000Z',
      type: 'session_meta',
      payload: { id: CODEX_THREAD, cwd: '/Users/me/garden', originator: 'codex_cli_rs' },
    },
    {
      timestamp: '2026-04-02T09:00:00.100Z',
      type: 'turn_context',
      payload: { model: 'gpt-5-codex', cwd: '/Users/me/garden' },
    },
    {
      timestamp: '2026-04-02T09:00:01.000Z',
      type: 'response_item',
      payload: {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: '<environment_context>cwd</environment_context>' }],
      },
    },
    {
      timestamp: '2026-04-02T09:00:02.000Z',
      type: 'response_item',
      payload: {
        type: 'message',
        role: 'user',
        content: [{ type: 'input_text', text: 'Plan the watering schedule' }],
      },
    },
    {
      timestamp: '2026-04-02T09:00:02.000Z',
      type: 'event_msg',
      payload: { type: 'user_message', message: 'Plan the watering schedule' },
    },
    {
      timestamp: '2026-04-02T09:00:03.000Z',
      type: 'response_item',
      payload: { type: 'reasoning', summary: [] },
    },
    {
      timestamp: '2026-04-02T09:00:04.000Z',
      type: 'response_item',
      payload: { type: 'function_call', name: 'shell', arguments: '{}', call_id: 'c' },
    },
    {
      timestamp: '2026-04-02T09:00:05.000Z',
      type: 'response_item',
      payload: {
        type: 'message',
        role: 'assistant',
        content: [{ type: 'output_text', text: 'Water the tomatoes at dawn.' }],
      },
    },
    {
      timestamp: '2026-04-02T09:00:05.000Z',
      type: 'event_msg',
      payload: { type: 'agent_message', message: 'Water the tomatoes at dawn.' },
    },
  ];
  write(
    join(dir, 'sessions', '2026', '04', '02', `rollout-2026-04-02T09-00-00-${CODEX_THREAD}.jsonl`),
    jsonl(lines),
  );
  // Older, squeezed, and from before the wrapper: the item is the line.
  const old = '11111111-2222-3333-4444-555555555555';
  write(
    join(dir, 'sessions', '2025', '12', '01', `rollout-2025-12-01T08-00-00-${old}.jsonl.zst`),
    zstdCompressSync(
      Buffer.from(
        jsonl([
          { id: old, timestamp: '2025-12-01T08:00:00.000Z', instructions: '' },
          {
            type: 'message',
            role: 'user',
            content: [{ type: 'input_text', text: 'Rename the photos by date' }],
          },
          {
            type: 'message',
            role: 'assistant',
            content: [{ type: 'output_text', text: 'Done: 42 photos renamed.' }],
          },
        ]),
      ),
    ),
  );
  write(
    join(dir, 'session_index.jsonl'),
    jsonl([{ id: CODEX_THREAD, thread_name: 'Garden watering', updated_at: '2026-04-02' }]),
  );
}

/** `~/.gemini/tmp/<project>/chats/`: the change log, and a whole file from before it. */
export function geminiHome(home: string) {
  const dir = join(home, '.gemini');
  write(join(dir, 'projects.json'), JSON.stringify({ projects: { '/Users/me/novel': 'novel' } }));
  write(
    join(dir, 'tmp', 'novel', 'chats', 'session-2026-05-01T10-00-abcd1234.jsonl'),
    jsonl([
      {
        sessionId: 'abcd1234-0000',
        projectHash: 'novel',
        startTime: '2026-05-01T10:00:00.000Z',
        lastUpdated: '2026-05-01T10:05:00.000Z',
        kind: 'main',
      },
      {
        id: 'u1',
        timestamp: '2026-05-01T10:00:00.000Z',
        type: 'user',
        content: [{ text: 'Name the villain' }],
      },
      {
        id: 'g1',
        timestamp: '2026-05-01T10:00:02.000Z',
        type: 'gemini',
        content: 'Draft',
        model: 'gemini-2.5-pro',
      },
      // A later line with the same id replaces it.
      {
        id: 'g1',
        timestamp: '2026-05-01T10:00:03.000Z',
        type: 'gemini',
        content: [{ text: 'thinking', thought: true }, { text: 'Call her Mara Vell.' }],
        model: 'gemini-2.5-pro',
      },
      {
        id: 'u2',
        timestamp: '2026-05-01T10:01:00.000Z',
        type: 'user',
        content: 'Something I took back',
      },
      { $rewindTo: 'u2' },
      { id: 'i1', timestamp: '2026-05-01T10:01:30.000Z', type: 'info', content: 'Model switched' },
      { $set: { summary: 'Naming the villain' } },
    ]),
  );
  write(
    join(dir, 'tmp', 'a'.repeat(64), 'chats', 'session-2025-11-01T09-00-old.json'),
    JSON.stringify({
      sessionId: 'old-0000',
      startTime: '2025-11-01T09:00:00.000Z',
      messages: [
        {
          id: 'a',
          timestamp: '2025-11-01T09:00:00.000Z',
          type: 'user',
          content: 'Translate the letter',
        },
        {
          id: 'b',
          timestamp: '2025-11-01T09:00:04.000Z',
          type: 'gemini',
          content: 'Here it is in French.',
        },
      ],
    }),
  );
  // A helper's session isn't yours.
  write(
    join(dir, 'tmp', 'novel', 'chats', 'session-2026-05-01T11-00-helper00.jsonl'),
    jsonl([
      { sessionId: 'helper', startTime: '2026-05-01T11:00:00.000Z', kind: 'subagent' },
      { id: 'h', type: 'user', content: 'helper task' },
    ]),
  );
}

/** `~/.local/share/opencode/opencode.db`, and a session from before the database. */
export function openCodeHome(home: string) {
  const dir = join(home, '.local', 'share', 'opencode');
  mkdirSync(dir, { recursive: true });
  const db = new DatabaseSync(join(dir, 'opencode.db'));
  db.exec(`
    CREATE TABLE session (id TEXT PRIMARY KEY, project_id TEXT, parent_id TEXT, directory TEXT, title TEXT,
      time_created INTEGER, time_updated INTEGER);
    CREATE TABLE message (id TEXT PRIMARY KEY, session_id TEXT, time_created INTEGER, data TEXT);
    CREATE TABLE part (id TEXT PRIMARY KEY, message_id TEXT, session_id TEXT, data TEXT);
  `);
  db.prepare('INSERT INTO session VALUES (?, ?, ?, ?, ?, ?, ?)').run(
    'ses_1',
    'p',
    null,
    '/Users/me/api',
    'Rate limits',
    1_750_000_000_000,
    1_750_000_100_000,
  );
  db.prepare('INSERT INTO session VALUES (?, ?, ?, ?, ?, ?, ?)').run(
    'ses_child',
    'p',
    'ses_1',
    '/Users/me/api',
    'Subtask',
    1_750_000_000_000,
    1_750_000_100_000,
  );
  const msg = db.prepare('INSERT INTO message VALUES (?, ?, ?, ?)');
  msg.run('msg_1', 'ses_1', 1_750_000_000_000, JSON.stringify({ role: 'user' }));
  msg.run(
    'msg_2',
    'ses_1',
    1_750_000_050_000,
    JSON.stringify({ role: 'assistant', modelID: 'claude-opus-4' }),
  );
  const part = db.prepare('INSERT INTO part VALUES (?, ?, ?, ?)');
  part.run(
    'prt_1',
    'msg_1',
    'ses_1',
    JSON.stringify({ type: 'text', text: 'Add a rate limit to the API' }),
  );
  part.run(
    'prt_2',
    'msg_1',
    'ses_1',
    JSON.stringify({ type: 'text', text: 'added by the app', synthetic: true }),
  );
  part.run('prt_3', 'msg_2', 'ses_1', JSON.stringify({ type: 'tool', tool: 'edit', state: {} }));
  part.run(
    'prt_4',
    'msg_2',
    'ses_1',
    JSON.stringify({ type: 'text', text: 'Added: 100 requests a minute.' }),
  );
  db.close();
  const storage = join(dir, 'storage');
  write(
    join(storage, 'session', 'proj', 'ses_old.json'),
    JSON.stringify({
      id: 'ses_old',
      title: 'Old one',
      directory: '/Users/me/blog',
      time: { created: 1_700_000_000_000, updated: 1_700_000_100_000 },
    }),
  );
  write(
    join(storage, 'message', 'ses_old', 'msg_a.json'),
    JSON.stringify({ id: 'msg_a', role: 'user', time: { created: 1_700_000_000_000 } }),
  );
  write(
    join(storage, 'message', 'ses_old', 'msg_b.json'),
    JSON.stringify({ id: 'msg_b', role: 'assistant', time: { created: 1_700_000_001_000 } }),
  );
  write(
    join(storage, 'part', 'msg_a', 'prt_a.json'),
    JSON.stringify({ type: 'text', text: 'Fix the RSS feed' }),
  );
  write(
    join(storage, 'part', 'msg_b', 'prt_b.json'),
    JSON.stringify({ type: 'text', text: 'The feed is valid now.' }),
  );
}

/** `~/.openclaw/agents/main/agent/openclaw-agent.sqlite` (one transcript squeezed), and an older file. */
export function openClawChatsHome(home: string) {
  const dir = join(home, '.openclaw', 'agents', 'main');
  mkdirSync(join(dir, 'agent'), { recursive: true });
  const db = new DatabaseSync(join(dir, 'agent', 'openclaw-agent.sqlite'));
  db.exec(`
    CREATE TABLE session_nodes (session_key TEXT PRIMARY KEY, current_session_id TEXT, entry_json TEXT,
      updated_at INTEGER, created_via TEXT);
    CREATE TABLE session_windows (session_id TEXT PRIMARY KEY, session_key TEXT, session_scope TEXT,
      created_at INTEGER, updated_at INTEGER);
    CREATE TABLE transcript_events (session_id TEXT, seq INTEGER, event_json TEXT, created_at INTEGER,
      event_zstd BLOB, PRIMARY KEY (session_id, seq));
  `);
  db.prepare('INSERT INTO session_nodes VALUES (?, ?, ?, ?, ?)').run(
    'k1',
    's1',
    '{}',
    1_760_000_000_000,
    'operator',
  );
  db.prepare('INSERT INTO session_nodes VALUES (?, ?, ?, ?, ?)').run(
    'k2',
    's2',
    '{}',
    1_760_000_000_000,
    'cron',
  );
  db.prepare('INSERT INTO session_nodes VALUES (?, ?, ?, ?, ?)').run(
    'k3',
    's3',
    '{}',
    1_760_000_000_000,
    'channel',
  );
  const win = db.prepare('INSERT INTO session_windows VALUES (?, ?, ?, ?, ?)');
  win.run('s1', 'k1', 'conversation', 1_760_000_000_000, 1_760_000_100_000);
  win.run('s2', 'k2', 'conversation', 1_760_000_000_000, 1_760_000_100_000);
  win.run('s3', 'k3', 'group', 1_760_000_000_000, 1_760_000_100_000);
  const ev = db.prepare('INSERT INTO transcript_events VALUES (?, ?, ?, ?, ?)');
  ev.run(
    's1',
    0,
    JSON.stringify({ type: 'session', version: 3, id: 's1', cwd: '/Users/me/trip' }),
    1,
    null,
  );
  ev.run('s1', 1, JSON.stringify({ type: 'session_info', name: 'Lisbon trip' }), 1, null);
  ev.run(
    's1',
    2,
    JSON.stringify({
      type: 'message',
      timestamp: '2026-06-01T08:00:00.000Z',
      message: { role: 'user', content: 'Find a hotel near Alfama' },
    }),
    1,
    null,
  );
  ev.run(
    's1',
    3,
    null,
    1,
    zstdCompressSync(
      Buffer.from(
        JSON.stringify({
          type: 'message',
          timestamp: '2026-06-01T08:00:09.000Z',
          message: {
            role: 'assistant',
            model: 'claude-opus-4',
            content: [{ type: 'text', text: 'Memmo Alfama has a terrace.' }],
          },
        }),
      ),
    ),
  );
  ev.run(
    's1',
    4,
    JSON.stringify({ type: 'message', message: { role: 'toolResult', content: 'search results' } }),
    1,
    null,
  );
  ev.run(
    's2',
    0,
    JSON.stringify({ type: 'message', message: { role: 'user', content: 'cron prompt' } }),
    1,
    null,
  );
  ev.run(
    's3',
    0,
    JSON.stringify({
      type: 'message',
      message: { role: 'user', content: 'someone else in a group' },
    }),
    1,
    null,
  );
  db.close();
  write(
    join(dir, 'sessions', 'legacy-1.jsonl'),
    jsonl([
      {
        type: 'session',
        version: 2,
        id: 'legacy-1',
        timestamp: '2025-10-01T08:00:00.000Z',
        cwd: '/Users/me',
      },
      {
        type: 'message',
        timestamp: '2025-10-01T08:00:00.000Z',
        message: { role: 'user', content: 'Remind me about the dentist' },
      },
      {
        type: 'message',
        timestamp: '2025-10-01T08:00:01.000Z',
        message: { role: 'assistant', content: [{ type: 'text', text: 'Tuesday at 9.' }] },
      },
    ]),
  );
}

/** `~/.hermes/state.db`, with a routine's run that isn't a chat of yours. */
export function hermesChatsHome(home: string) {
  const dir = join(home, '.hermes');
  mkdirSync(dir, { recursive: true });
  const db = new DatabaseSync(join(dir, 'state.db'));
  db.exec(`
    CREATE TABLE sessions (id TEXT PRIMARY KEY, source TEXT NOT NULL, model TEXT, title TEXT,
      parent_session_id TEXT, started_at REAL NOT NULL, ended_at REAL, message_count INTEGER, cwd TEXT);
    CREATE TABLE messages (id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL, role TEXT NOT NULL,
      content TEXT, tool_calls TEXT, timestamp REAL NOT NULL, codex_message_items TEXT);
  `);
  const s = db.prepare('INSERT INTO sessions VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)');
  s.run(
    '20260701_090000_ab',
    'cli',
    'hermes-4',
    'Tax return',
    null,
    1_782_896_400,
    1_782_896_500,
    3,
    '/Users/me/tax',
  );
  s.run(
    '20260701_100000_cd',
    'cron',
    'hermes-4',
    'Daily brief',
    null,
    1_782_900_000,
    1_782_900_100,
    2,
    null,
  );
  const m = db.prepare(
    'INSERT INTO messages (session_id, role, content, tool_calls, timestamp, codex_message_items) VALUES (?, ?, ?, ?, ?, ?)',
  );
  m.run('20260701_090000_ab', 'user', 'Which receipts do I need?', null, 1_782_896_400, null);
  m.run('20260701_090000_ab', 'tool', 'ls output', null, 1_782_896_401, null);
  m.run(
    '20260701_090000_ab',
    'assistant',
    '',
    null,
    1_782_896_402,
    JSON.stringify([
      {
        type: 'message',
        role: 'assistant',
        content: [{ type: 'output_text', text: 'Keep the pharmacy ones.' }],
      },
    ]),
  );
  m.run('20260701_100000_cd', 'user', 'brief me', null, 1_782_900_000, null);
  db.close();
}

/** VS Code's Copilot Chat: a whole session file, and a newer change log. */
export function copilotHome(home: string) {
  const user =
    process.platform === 'darwin'
      ? join(home, 'Library', 'Application Support', 'Code', 'User')
      : process.platform === 'win32'
        ? join(home, 'AppData', 'Roaming', 'Code', 'User')
        : join(home, '.config', 'Code', 'User');
  const ws = join(user, 'workspaceStorage', 'abc123');
  write(join(ws, 'workspace.json'), JSON.stringify({ folder: 'file:///Users/me/site' }));
  write(
    join(ws, 'chatSessions', 'one.json'),
    JSON.stringify({
      sessionId: 'one',
      creationDate: 1_755_000_000_000,
      requests: [
        {
          message: { text: 'Center the header' },
          timestamp: 1_755_000_000_000,
          response: [{ value: 'Use ' }, { kind: 'inlineReference' }, { value: 'flexbox.' }],
          result: { metadata: { modelId: 'gpt-4.1' } },
        },
      ],
    }),
  );
  write(
    join(ws, 'chatSessions', 'two.jsonl'),
    jsonl([
      { kind: 0, v: { sessionId: 'two', creationDate: 1_756_000_000_000, requests: [] } },
      {
        kind: 2,
        k: ['requests'],
        v: [
          {
            message: { text: 'Why is the build slow?' },
            timestamp: 1_756_000_000_000,
            response: [],
          },
        ],
      },
      {
        kind: 2,
        k: ['requests', 0, 'response'],
        v: [{ kind: 'markdownContent', content: { value: 'Source maps are on.' } }],
      },
      { kind: 1, k: ['__proto__', 'polluted'], v: true },
      { kind: 1, k: ['customTitle'], v: 'Slow build' },
    ]),
  );
}

/** Every app at once. */
export function everyAppHome(home: string) {
  claudeHome(home);
  codexHome(home);
  geminiHome(home);
  openCodeHome(home);
  copilotHome(home);
  openClawChatsHome(home);
  hermesChatsHome(home);
}
